language: php
php:
  - 7.1
  - 7.2
  - nightly
sudo: false

env:

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

jobs:
  include:
    - stage: test
      before_script:
        - wget https://phar.phpunit.de/phpunit.phar
      script:
        - php phpunit.phar --no-coverage

    - stage: coverage
      php: 7.1
      before_script:
        - wget https://phar.phpunit.de/phpunit.phar
      script:
        - php phpunit.phar
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php coveralls.phar --verbose
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.1/php-coveralls.phar && php coveralls.phar --verbose
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.1.0/php-coveralls.phar && php coveralls.phar --verbose
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar && php coveralls.phar --verbose

    - stage: lint
      php: 7.1
      before_script:
        - wget https://github.com/phpstan/phpstan/releases/download/0.9.1/phpstan.phar
      script:
        - php phpstan.phar analyse src --level max --configuration phpstan.neon
        - composer create-project symplify/easy-coding-standard temp/ecs && temp/ecs/bin/ecs check src tests

cache:
  directories:
  - $HOME/.composer/cache/files

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
